/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interface.Network;

import Business.Business;
import Business.Network.Network;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author yufeng
 */
public class NetworkWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NetworkWorkAreaJPanel
     */
    JPanel userProcessContainer;
    Network network;
    Business business;
    UserAccount userAccount;
    public NetworkWorkAreaJPanel(JPanel userProcessContainer,UserAccount userAccount,Network network,Business business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.network = network;
        this.business = business;
        this.userAccount = userAccount;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        insuranceJButton1 = new javax.swing.JButton();
        manageDiseaseJButton = new javax.swing.JButton();
        enterpriseJButton = new javax.swing.JButton();
        addNationalUserAccountJButton1 = new javax.swing.JButton();

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/United-Nations-Flag-1-icon.png"))); // NOI18N

        insuranceJButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        insuranceJButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Folder-icon.png"))); // NOI18N
        insuranceJButton1.setText("Manage Insurance");
        insuranceJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insuranceJButton1ActionPerformed(evt);
            }
        });

        manageDiseaseJButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        manageDiseaseJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Folder-icon.png"))); // NOI18N
        manageDiseaseJButton.setText("Manage National Diseases");
        manageDiseaseJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageDiseaseJButtonActionPerformed(evt);
            }
        });

        enterpriseJButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        enterpriseJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Folder-icon.png"))); // NOI18N
        enterpriseJButton.setText("Manage National Enterprise");
        enterpriseJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterpriseJButtonActionPerformed(evt);
            }
        });

        addNationalUserAccountJButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addNationalUserAccountJButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Folder-icon.png"))); // NOI18N
        addNationalUserAccountJButton1.setText("Manage Enterprise User Account");
        addNationalUserAccountJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNationalUserAccountJButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addNationalUserAccountJButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                    .addComponent(enterpriseJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(insuranceJButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageDiseaseJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enterpriseJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(addNationalUserAccountJButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(insuranceJButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(manageDiseaseJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel2)))
                .addContainerGap(208, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void enterpriseJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterpriseJButtonActionPerformed
        // TODO add your handling code here:
        NetworkManageEnterprise nme = new NetworkManageEnterprise(userProcessContainer,network);
        userProcessContainer.add("NetworkManageEnterprise",nme);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_enterpriseJButtonActionPerformed

    private void addNationalUserAccountJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNationalUserAccountJButton1ActionPerformed
        // TODO add your handling code here:
        ManageEnterpriseUserAccount adua = new ManageEnterpriseUserAccount(userProcessContainer,network);
        userProcessContainer.add("AddUserAccount",adua);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_addNationalUserAccountJButton1ActionPerformed

    private void insuranceJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insuranceJButton1ActionPerformed
        // TODO add your handling code here:
        ManageInsurance mi = new ManageInsurance(userProcessContainer,network);
        userProcessContainer.add("ManageInsurance",mi);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_insuranceJButton1ActionPerformed

    private void manageDiseaseJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageDiseaseJButtonActionPerformed
        // TODO add your handling code here:
        ManageNationalDiseases mnd = new ManageNationalDiseases(userProcessContainer,business);
        userProcessContainer.add("ManageNationalDiseases",mnd);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_manageDiseaseJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNationalUserAccountJButton1;
    private javax.swing.JButton enterpriseJButton;
    private javax.swing.JButton insuranceJButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton manageDiseaseJButton;
    // End of variables declaration//GEN-END:variables
}
