/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interface.Distributor;

import Business.Enterprise.Enterprise;
import Business.Manufactrurer.Manufacturer;
import Business.Manufactrurer.ManufacturerVaccineSaleItem;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Role.ManufacturerRole;
import Business.UserAccount.UserAccount;
import Business.WorkRequest.ClinicRequest;
import Business.WorkRequest.VaccineRequestItem;
import Business.WorkRequest.WorkRequest;
import Interface.MainJFrame1;
import java.awt.CardLayout;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yufeng
 */
public class ShipConfirmJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ShipConfirmJPanel
     */
    JPanel userProcessContainer;
    WorkRequest workRequest;
    Network network;
    public ShipConfirmJPanel(JPanel userProcessContainer,Network network, WorkRequest workRequest) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.workRequest = workRequest;
        populateVaccineJTable();
        this.network = network;
        ClinicNameJTextField.setText(((ClinicRequest)workRequest).getClinicName());
    }

    
    public void populateVaccineJTable(){
        DefaultTableModel dtm = (DefaultTableModel) VaccineItemJTable.getModel();
        dtm.setRowCount(0);
        for(VaccineRequestItem vaccineRequestItem : ((ClinicRequest)workRequest).getVaccineRequestItemList()){
            Object[] row = new Object[3];
            row[0] = vaccineRequestItem.getVaccine().getVaccineID();
            row[1] = vaccineRequestItem.getVaccine();
            row[2] = vaccineRequestItem.getVaccine().getManufacturerName();
            dtm.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        VaccineItemJTable = new javax.swing.JTable();
        approveJButton1 = new javax.swing.JButton();
        ClinicNameJTextField = new javax.swing.JLabel();
        goMapJButton = new javax.swing.JButton();
        backJButton1 = new javax.swing.JButton();

        VaccineItemJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vaccine ID", "Vaccine Name", "Manufacturer Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(VaccineItemJTable);

        approveJButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        approveJButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Transport-Historic-Ship-icon.png"))); // NOI18N
        approveJButton1.setText("Ship");
        approveJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveJButton1ActionPerformed(evt);
            }
        });

        ClinicNameJTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ClinicNameJTextField.setText("jLabel1");

        goMapJButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        goMapJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search-icon.png"))); // NOI18N
        goMapJButton.setText("Go Map");
        goMapJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goMapJButtonActionPerformed(evt);
            }
        });

        backJButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backJButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back-3-icon.png"))); // NOI18N
        backJButton1.setText("Back");
        backJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backJButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap(217, Short.MAX_VALUE)
                            .addComponent(approveJButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(121, 121, 121)
                            .addComponent(goMapJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(37, 37, 37)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ClinicNameJTextField)))))
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(ClinicNameJTextField)
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(approveJButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(goMapJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(backJButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void approveJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveJButton1ActionPerformed
        // TODO add your handling code here:
        workRequest.setStatus("Shipped");
        for(VaccineRequestItem item : ((ClinicRequest)workRequest).getVaccineRequestItemList()){
            for(Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()){
                if(enterprise instanceof Manufacturer){
                    if(enterprise.getName().equals(item.getVaccine().getManufacturerName())){
                        ManufacturerVaccineSaleItem manufacturerVaccineSaleItem = new ManufacturerVaccineSaleItem();
                        manufacturerVaccineSaleItem.setAmount(item.getAmount());
                        manufacturerVaccineSaleItem.setVaccine(item.getVaccine());
                        manufacturerVaccineSaleItem.setVaccineSaleTime(manufacturerVaccineSaleItem.getTimestampe());
                        manufacturerVaccineSaleItem.setType("Clinic Request");
                        ((ManufacturerRole)enterprise.getUserAccountDirectory().getUserAccountList().get(0).getRole()).getManufacturerVaccineSaleItemList().add(manufacturerVaccineSaleItem);
                    }
                }
            }
        }
        JOptionPane.showMessageDialog(null,"Successfully!");
        populateVaccineJTable();
        
    }//GEN-LAST:event_approveJButton1ActionPerformed

    private void goMapJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goMapJButtonActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            
            String url = "https://www.google.com/maps/";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(url));
            
        } catch (IOException ex) {
            Logger.getLogger(MainJFrame1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_goMapJButtonActionPerformed

    private void backJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ClinicNameJTextField;
    private javax.swing.JTable VaccineItemJTable;
    private javax.swing.JButton approveJButton1;
    private javax.swing.JButton backJButton1;
    private javax.swing.JButton goMapJButton;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
