/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interface.SysAdmin;

import Business.Business;
import Business.Network.Network;
import Business.UserAccount.UserAccount;
import Interface.Hospital_CVS.EditHospitalOrgUserAccount;
import Interface.Hospital_CVS.ViewClinicEmployee;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yufeng
 */
public class ManageNetworkUserAccount extends javax.swing.JPanel {

    /**
     * Creates new form ManageNetworkUserAccount
     */
    JPanel userProcessContainer;
    Business business;
    public ManageNetworkUserAccount(JPanel userProcessContainer,Business business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        populateNetworkJTabel();
        populateUserJTable();
    }

    public void populateNetworkJTabel(){
        DefaultTableModel dtm = (DefaultTableModel) networkJTable.getModel();
        dtm.setRowCount(0);
        for(Network network : business.getNetworkDirectory().getNetworkList()){
            if(network.getStatus().equals("Active")){
                Object[] row = new Object[3];
                row[0] = network.getOrganizationID();
                row[1] = network;
                row[2] = network.getStatus();
                dtm.addRow(row);
            }    
        }
    }
    
    public void populateUserJTable(){
        DefaultTableModel dtm = (DefaultTableModel) userJTable.getModel();
        dtm.setRowCount(0);
        for(Network network : business.getNetworkDirectory().getNetworkList()){
            if(network.getStatus().equals("Active")){
                for(UserAccount userAccount : network.getUserAccountDirectory().getUserAccountList()){
                    Object[] row = new Object[3];
                    row[0] = network.getOrganizationID();
                    row[1] = network;
                    row[2] = userAccount;
                    dtm.addRow(row);
                }
                    
            }    
        }
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addNationalUserAccountJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        networkJTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        userJTable = new javax.swing.JTable();
        viewJButton4 = new javax.swing.JButton();
        editJButton1 = new javax.swing.JButton();
        deleteJButton1 = new javax.swing.JButton();
        refreshJButton2 = new javax.swing.JButton();
        backJButton1 = new javax.swing.JButton();

        addNationalUserAccountJButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addNationalUserAccountJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button-Add-icon.png"))); // NOI18N
        addNationalUserAccountJButton.setText("Add User Account");
        addNationalUserAccountJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNationalUserAccountJButtonActionPerformed(evt);
            }
        });

        networkJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Network ID", "Network Name", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(networkJTable);

        userJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Network ID", "Network Name", "UserAccount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(userJTable);

        viewJButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        viewJButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Actions-view-list-details-icon.png"))); // NOI18N
        viewJButton4.setText("View Employee");
        viewJButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewJButton4ActionPerformed(evt);
            }
        });

        editJButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        editJButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit-icon.png"))); // NOI18N
        editJButton1.setText("Edit Employee Info");
        editJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editJButton1ActionPerformed(evt);
            }
        });

        deleteJButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deleteJButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Delete-icon.png"))); // NOI18N
        deleteJButton1.setText("Delete ");
        deleteJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteJButton1ActionPerformed(evt);
            }
        });

        refreshJButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        refreshJButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Reload-icon.png"))); // NOI18N
        refreshJButton2.setText("Refresh ");
        refreshJButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButton2ActionPerformed(evt);
            }
        });

        backJButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backJButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back-3-icon.png"))); // NOI18N
        backJButton1.setText("Back");
        backJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(203, 203, 203)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(editJButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(viewJButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(deleteJButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(refreshJButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(205, 205, 205)
                                .addComponent(addNationalUserAccountJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(backJButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addNationalUserAccountJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewJButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(editJButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deleteJButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(refreshJButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(backJButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addNationalUserAccountJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNationalUserAccountJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = networkJTable.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null,"Please select a Row!");
        }
        else{
           Network network = (Network) networkJTable.getValueAt(selectedRow, 1);
            AddNationalNetworkUseraccount adua = new AddNationalNetworkUseraccount(userProcessContainer,network,business);
            userProcessContainer.add("AddNationalUseraccount", adua);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer); 
        }
        
    }//GEN-LAST:event_addNationalUserAccountJButtonActionPerformed

    private void viewJButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewJButton4ActionPerformed
        // TODO add your handling code here:
        int selectedRow = userJTable.getSelectedRow();
        if(selectedRow < 0 ){
            JOptionPane.showMessageDialog(null, "Please select a row!");
        }
        else{

            UserAccount userAccount = (UserAccount) userJTable.getValueAt(selectedRow, 2);
            ViewClinicEmployee vo = new ViewClinicEmployee(userProcessContainer,userAccount);
            userProcessContainer.add("ViewOrganizationUserAccount",vo);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_viewJButton4ActionPerformed

    private void editJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editJButton1ActionPerformed
        // TODO add your handling code here:
        int selectedRow = userJTable.getSelectedRow();
        if(selectedRow < 0 ){
            JOptionPane.showMessageDialog(null, "Please select a valid UserAccount");
        }
        else{
            UserAccount userAccount = (UserAccount) userJTable.getValueAt(selectedRow, 2);
            EditHospitalOrgUserAccount eua = new EditHospitalOrgUserAccount(userProcessContainer,userAccount);
            userProcessContainer.add("EditHospitalOrgUserAccount", eua);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_editJButton1ActionPerformed

    private void deleteJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteJButton1ActionPerformed
        // TODO add your handling code here:
        int selectedRow = userJTable.getSelectedRow();
        if(selectedRow < 0 ){
            JOptionPane.showMessageDialog(null, "Please select a User first!");
        }
        else{
            UserAccount userAccounthere = (UserAccount) userJTable.getValueAt(selectedRow,2);
            Network networkhere = (Network) userJTable.getValueAt(selectedRow, 1);
            int p =  JOptionPane.showConfirmDialog(null, "Do you want to delete this?","Delete",JOptionPane.YES_NO_OPTION);
            if(p == 0){
                networkhere.getUserAccountDirectory().getUserAccountList().remove(userAccounthere);
            }

        }
    }//GEN-LAST:event_deleteJButton1ActionPerformed

    private void refreshJButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButton2ActionPerformed
        // TODO add your handling code here:
        populateUserJTable();
        populateNetworkJTabel();
    }//GEN-LAST:event_refreshJButton2ActionPerformed

    private void backJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNationalUserAccountJButton;
    private javax.swing.JButton backJButton1;
    private javax.swing.JButton deleteJButton1;
    private javax.swing.JButton editJButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable networkJTable;
    private javax.swing.JButton refreshJButton2;
    private javax.swing.JTable userJTable;
    private javax.swing.JButton viewJButton4;
    // End of variables declaration//GEN-END:variables
}
