/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interface.SysAdmin;

import Business.Business;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author yufeng
 */
public class SysAdminWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form SysAdminWorkArea
     */
    private JPanel userProcessContainer;
    private Business business;
   
    public SysAdminWorkArea(JPanel userProcessContainer,Business business) {
        
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        populateTree();
    }
    private void populateTree() {

        DefaultTreeModel model = (DefaultTreeModel) Jtree.getModel();
        
        ArrayList<Network> networkList = business.getNetworkDirectory().getNetworkList();
        ArrayList<Enterprise> enterpriseList;
        ArrayList<Organization> organizationList;
        Network network;
        Enterprise enterprise;
        Organization organization;

        
        DefaultMutableTreeNode root = (DefaultMutableTreeNode) model.getRoot();
        root.removeAllChildren();

        DefaultMutableTreeNode networkNode;
        DefaultMutableTreeNode enterpriseNode;
        DefaultMutableTreeNode organizationNode;
        
            for (int i = 0; i < networkList.size(); i++) {
                network = networkList.get(i);
                networkNode = new DefaultMutableTreeNode(network.getNetworkName());
                root.insert(networkNode, i);

                enterpriseList = network.getEnterpriseDirectory().getEnterpriseList();

                for (int j = 0; j < enterpriseList.size(); j++) {
                    enterprise = enterpriseList.get(j);
                    enterpriseNode = new DefaultMutableTreeNode(enterprise.getName());
                    networkNode.insert(enterpriseNode, j);

                    organizationList = enterprise.getOrganizationDirectory().getOrganizationList();
                    for (int k = 0; k < organizationList.size(); k++) {
                        organization = organizationList.get(k);
                        organizationNode = new DefaultMutableTreeNode(organization.getName());
                        enterpriseNode.insert(organizationNode, k);
                    }
                }
            }

          model.reload();
        
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Jtree = new javax.swing.JTree();
        networkJButton = new javax.swing.JButton();
        enterpriseJButton = new javax.swing.JButton();
        manageNationalUserAccountJButton = new javax.swing.JButton();
        refreshJButton1 = new javax.swing.JButton();
        manageNationalUserAccountJButton1 = new javax.swing.JButton();

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("System");
        Jtree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(Jtree);

        networkJButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        networkJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Folder-icon.png"))); // NOI18N
        networkJButton.setText("Manage National Network");
        networkJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkJButtonActionPerformed(evt);
            }
        });

        enterpriseJButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        enterpriseJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Folder-icon.png"))); // NOI18N
        enterpriseJButton.setText("Manage National Enterprise");
        enterpriseJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterpriseJButtonActionPerformed(evt);
            }
        });

        manageNationalUserAccountJButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        manageNationalUserAccountJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Folder-icon.png"))); // NOI18N
        manageNationalUserAccountJButton.setText("Manage Network User Account");
        manageNationalUserAccountJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageNationalUserAccountJButtonActionPerformed(evt);
            }
        });

        refreshJButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        refreshJButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Reload-icon.png"))); // NOI18N
        refreshJButton1.setText("Refresh Model");
        refreshJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButton1ActionPerformed(evt);
            }
        });

        manageNationalUserAccountJButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        manageNationalUserAccountJButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Folder-icon.png"))); // NOI18N
        manageNationalUserAccountJButton1.setText("Manage Enterprise User Account");
        manageNationalUserAccountJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageNationalUserAccountJButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(networkJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(enterpriseJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageNationalUserAccountJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(refreshJButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageNationalUserAccountJButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(networkJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(enterpriseJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(manageNationalUserAccountJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(manageNationalUserAccountJButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(refreshJButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void enterpriseJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterpriseJButtonActionPerformed
        // TODO add your handling code here:
        ManageEnterprise me = new ManageEnterprise(userProcessContainer, business);
        userProcessContainer.add("ManageEnterprise",me);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_enterpriseJButtonActionPerformed

    private void networkJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkJButtonActionPerformed
        // TODO add your handling code here:
        ManageNetwork mn = new ManageNetwork(userProcessContainer, business);
        userProcessContainer.add("ManageNetwork",mn);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_networkJButtonActionPerformed

    private void manageNationalUserAccountJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageNationalUserAccountJButtonActionPerformed
        // TODO add your handling code here:
        ManageNetworkUserAccount adua = new ManageNetworkUserAccount(userProcessContainer,business);
        userProcessContainer.add("AddNationalUseraccount", adua);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageNationalUserAccountJButtonActionPerformed

    private void refreshJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButton1ActionPerformed
        // TODO add your handling code here:
        populateTree();
    }//GEN-LAST:event_refreshJButton1ActionPerformed

    private void manageNationalUserAccountJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageNationalUserAccountJButton1ActionPerformed
        // TODO add your handling code here:
        ManageEnterpriseUserAccount addua = new ManageEnterpriseUserAccount(userProcessContainer,business);
        userProcessContainer.add("AddNationalEnterpriseUserAccount",addua);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_manageNationalUserAccountJButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree Jtree;
    private javax.swing.JButton enterpriseJButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton manageNationalUserAccountJButton;
    private javax.swing.JButton manageNationalUserAccountJButton1;
    private javax.swing.JButton networkJButton;
    private javax.swing.JButton refreshJButton1;
    // End of variables declaration//GEN-END:variables
}
